config/routes.rb
Justrate::Application.routes.draw do

  get "reviews/new" => "reviews#new_blank"
  post "reviews/create_blank" => "reviews#create_blank"
  get "users/new"
  get "users/create"

  get '/about_us' => 'static_page#about_us'
  get '/privacy' => 'static_page#privacy'
  get '/toc' => 'static_page#toc'

  devise_for :users, :controllers => {:confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    post "/confirm" => "confirmations#confirm"
  end

  devise_for :admins

  resources :users, :only => [:show, :edit, :update]
  resources :departments do
    get :course_list
  end
  resources :universities

  resources :courses do
    resources :reviews do
      member do
        post :vote_for
        post :vote_against
        post :flag
      end
      resources :comments, :shallow => true do
        get :reply
        post :new_reply
      end
    end
  end

  root :to => 'courses#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_ancestry

  attr_accessible :content, :user, :review_id, :parent_id

  belongs_to :review

  validates :content, presence: true

  def self.roots
    scoped.where(ancestry: nil)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # Make sure the user is authenticated
  before_filter :authenticate_user!, except: [:index, :show, :destroy, :update]
  before_filter :authenticate_admin!, only: [:destroy, :update]

  # GET /comments
  # GET /comments.json
  def index
    @course = Course.find(params[:course_id])
    @review = Review.find(params[:review_id])
    @comments = @review.comments.arrane(:order => :created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    
    @comment = Comment.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  def reply
    @comment = Comment.find(params[:comment_id])

    @reply = @comment.children.build

    respond_to do |format|
      format.html { render "reply_form" }
      format.json { render json: @comment }
      format.js { render partial: "reply", locals: { form: render_to_string("reply_form") } }
    end
  end

  def new_reply
    @comment = Comment.find(params[:comment_id])

    @reply = @comment.children.new(params[:comment])

    if @reply.save
      respond_to do |format|
        format.html { redirect_to course_review_path(@comment.review.course, @comment.review), notice: 'Comment was successfully created.' }
        format.json { render json: @comment }
      end
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @course = Course.find(params[:course_id])
    @review = @course.reviews.find(params[:review_id])
    @comment = @review.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to course_review_path(@course, @review), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to course_review_path(@comment.review.course, @comment.review), notice: 'Comment was successfully removed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def is_anonymous
		return current_user.anonComments
	end
end

app/views/comments/_comment.html.erb
<% if admin_signed_in? %>
  <%= link_to '<i class="icon-remove"></i>'.html_safe, comment_path(comment.id), method: :delete, confirm: 'Are you sure you want to remove this comment?' %>
<% end %>
<%= div_for(comment, class: "span12") do %>
  <div class="row-fluid">
      <div class ="user"> 
        <% if is_anonymous %>
          Anonymous
        <% else %>
          <%= link_to(current_user.name, current_user) %>
        <% end %>
      </div>
      <div class="created_at">
        <%= comment.created_at.strftime("%a %B %d, %Y, %H:%M") %>
      </div>
      <div class="content">
        <%= comment.content %>
      </div>
      <div class="new-reply">
      </div>
      
      <div class="actions">
        <%= link_to "Reply", comment_comment_reply_path(comment), remote: true %>
      </div>
  </div>
<% end %>
<div class="replies">
      <%= render comment.children %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@course, @review, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user, :value => current_user %>
  <%= f.input :content %>

  <div class="form-actions">
    <%= f.submit "Add comment", class: 'btn btn-success' %>
    <%= current_user.anonComments? ? 'as anonmous' : "as #{current_user.name}" %>
  </div>
<% end %>

app/views/comments/_reply.js.erb
$('#comment_<%= j @comment.id.to_s %> .new-reply').html('<%= j form.html_safe %>');

app/views/comments/reply_form.html.erb
<%= simple_form_for(@reply, url: comment_comment_new_reply_path(@comment)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <%= f.hidden_field :review_id, :value => @reply.parent.review.id %>

  <%= f.submit "Add comment", class: 'btn btn-success' %>
<% end %>