config/routes.rb
Justrate::Application.routes.draw do

  get "reviews/new" => "reviews#new_blank"
  post "reviews/create_blank" => "reviews#create_blank"
  get "users/new"
  get "users/create"

  get '/about_us' => 'static_page#about_us'
  get '/privacy' => 'static_page#privacy'
  get '/toc' => 'static_page#toc'

  devise_for :users, :controllers => {:confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    post "/confirm" => "confirmations#confirm"
  end

  devise_for :admins

  resources :users, :only => [:show, :edit, :update]
  resources :departments do
    get :course_list
  end
  resources :universities

  resources :courses do
    resources :reviews do
      member do
        post :vote_for
        post :vote_against
        post :flag
      end
      resources :comments, :shallow => true do
        get :reply
        post :new_reply
      end
    end
  end

  root :to => 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  # Make sure the user is authenticated
  #before_filter :authenticate_admin!, only: [:destroy, :update]
  before_filter :authenticate_admin!, except: [:show, :index]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.sorted_by_score
    @reviews = Review.sorted_by_created_at

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully removed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses.html.erb
<% if courses.empty? %>
  No courses added yet
<% else %>
  <table class="table">
    <thead>
      <th>Rank</th>
      <th>Name</th>
      <th>Lecturer</th>
      <th>Department</th>
      <th>Course number</th>
    </thead>
    <tbody>
      <% courses.each_with_index do |course, index| %>
        <tr>
          <td><%= index + 1 %></td>    
          <td><%= link_to course.name, course %></td>
          <td><%= course.lecturer %></td>
          <td><%= link_to course.department.name, course.department %></td>
          <td><%= course.course_number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/courses/_form.html.erb
<%= simple_nested_form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>Base information</legend>
  <%= f.input :name %><br />
  <%= f.input :course_number %>
  <%= f.input :department_id, collection: Department.all.collect { |d| [d.name, d.id] } %>
  <%= f.input :lecturer %>
  <%= f.input :description %>

  <%= f.fields_for :rating_entities do |rt_form| %>
    <%= rt_form.input :name %>
    <%= rt_form.input :description %>
    <%= rt_form.link_to_remove "Remove this entity" %>
  <% end %>
  <p>
    <%= f.link_to_add "Add a rating entity", :rating_entities %>
  </p>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>
<hr>
<%= render 'form' %>

app/views/courses/index.html.erb
<h1>
  <i class="icon-search"></i>
  <input id="course-search" type="search" placeholder="Search courses" class="span8 pull-left">
  </h1>
<hr>

<h1><i class="icon icon-trophy"></i>  Top 5 rated courses</h1>
<%= render partial: 'courses/courses', locals: { courses: @courses[0..4] } %>

<h1><i class="icon icon-time"></i>  Recent reviews</h1>
<%= render partial: 'reviews/reviews', locals: {reviews: @reviews[0..4] } %>

app/views/courses/new.html.erb
<h1>New course</h1>
<hr>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1>
  <% if admin_signed_in? %>
    <%= link_to '<i class="icon-remove"></i>'.html_safe, course_path(@course), method: :delete, confirm: 'Are you sure you want to remove this course?' %>
  <% end %>

  <%= @course.name %> (<%= @course.course_number %>)
</h1>
<p>
  <%= @course.description %>
</p>
<hr>
<h2>Reviews</h2>
<% @course.reviews.sort_by(&:votes_for).reverse.each do |review| %>
  <b>
    <%= link_to review.title, course_review_path(@course, review) %>
    |
    <i class='icon-thumbs-up'></i>
    <%= "#{review.votes_for}" %>
    <i class='icon-thumbs-down'/></i>
    <%= "#{review.votes_against}" %>
  </b>
  <p>
    <%= review.text %><br />
    (<%= l review.created_at, format: :long %>)
  </p>
<% end %>
<hr>
<%= link_to "Add review", new_course_review_path(@course), class: 'btn btn-primary' %>