config/routes.rb
Justrate::Application.routes.draw do

  get "reviews/new" => "reviews#new_blank"
  post "reviews/create_blank" => "reviews#create_blank"
  get "users/new"
  get "users/create"

  get '/about_us' => 'static_page#about_us'
  get '/privacy' => 'static_page#privacy'
  get '/toc' => 'static_page#toc'

  devise_for :users, :controllers => {:confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    post "/confirm" => "confirmations#confirm"
  end

  devise_for :admins

  resources :users, :only => [:show, :edit, :update]
  resources :departments do
    get :course_list
  end
  resources :universities

  resources :courses do
    resources :reviews do
      member do
        post :vote_for
        post :vote_against
        post :flag
      end
      resources :comments, :shallow => true do
        get :reply
        post :new_reply
      end
    end
  end

  root :to => 'courses#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  if Rails.env.development?
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, #:registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end

  # Setup accessible (or protected) attributes
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_ancestry

  attr_accessible :content, :user, :review_id, :parent_id

  belongs_to :review

  validates :content, presence: true

  def self.roots
    scoped.where(ancestry: nil)
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :course_number, :department_id, :rating_entities_attributes, :lecturer

  has_many :reviews, dependent: :destroy
  has_many :ratings, through: :reviews
  has_and_belongs_to_many :rating_entities

  belongs_to :department

  accepts_nested_attributes_for :rating_entities

  validates :description, :name, :course_number, :department_id, :lecturer, presence: true

  def self.sorted_by_score
    scoped.sort_by(&:average_score).reverse
  end

  def average_score
    if ratings.count > 0
      ratings.collect(&:score).sum / ratings.count
    else
      0
    end
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :university_id

  has_many :courses
  belongs_to :university

  validates :name, presence: true

end

app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :flagable, :polymorphic => true
  belongs_to :flager, polymorphic: true

  attr_accessible :description, :flagable, :flager, :type, :user_id
  validates_uniqueness_of :flagable_id, :scope => [:flagable_type, :flager_type, :flager_id]
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :rating_entity_id
  
  belongs_to :rating_entity
  belongs_to :review
  attr_accessible :score

  validates :score, presence: true
end

app/models/rating_entity.rb
class RatingEntity < ActiveRecord::Base
  attr_accessible :description, :name

  has_and_belongs_to_many :courses
  has_many :ratings
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :course_id, :text, :title, :ratings_attributes

  has_many :comments
  has_many :ratings

  accepts_nested_attributes_for :ratings
  
  belongs_to :course
  belongs_to :user

  acts_as_voteable
  
  has_many :flags, :as => :flagable
  
  validates :course_id, :text, :title, presence: true

  def self.sorted_by_created_at
    Review.all.sort_by(&:created_at).reverse
  end
end

app/models/university.rb
class University < ActiveRecord::Base
  attr_accessible :city, :country, :name

  has_many :departments
  has_many :courses, through: :departments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or passwordrotected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation,
                  :remember_me, :provider, :uid, :anonComments, :anonReviews

  validates :name, presence: true, on: :update

  has_many :flags, as: :flager
  has_many :flagged_reviews, through: :flags, source: :flagable, source_type: "Review"

  acts_as_voter

  def password_required?
    super if confirmed?
  end

  def anon_comments?
    anonComments
  end

  def anon_reviews?
    anonReviews
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def to_s
    name || email
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    data = auth.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password
      user = User.new(:name => data.name, :email => data.email, :password => Devise.friendly_token[0,20])
      user.skip_confirmation!
      user.save!
      user
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable

  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController

end

   
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def is_anonymous
		return current_user.anonComments
	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
		end.join.html_safe
	end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footernav.html.erb
<ul class="nav row-fluid">
  <li class="span3">
    <%= link_to "About us", about_us_path %>
  </li>
  <li class="span3">
    <%= link_to "Privacy policy", privacy_path %>
  </li>
  <li class="span3">
    <%= link_to "Terms & Conditions", toc_path %>
  </li>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav row-fluid">
  <li class="span3">
    <%= link_to "Add review", reviews_new_path %>
  </li>
  <li class="span3">
    <%= link_to "Courses", courses_path %>
  </li>
  <li class="span3">
    <%= link_to "Departments", departments_path %>
  </li>
  <li class="span3">
    <%= link_to "Universities", universities_path %>
  </li>
</ul>

app/views/layouts/_user.html.erb
<div class="row">
  <div class="span12 text-right">
    <% if user_signed_in? %>
      Logged in as <%= link_to current_user.name, user_path(current_user) %>, <%= link_to "Log out", destroy_user_session_path, :method => :delete %>

    <% elsif admin_signed_in? %>
      <span class="label label-warning">Admin</span>
      Logged in as <%= current_admin.email %>, <%= link_to "Log out", destroy_admin_session_path, :method => :delete %>

    <% else %>
    	<div class="login_div">
  			<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)%> |
 			<%= link_to "Sign in", user_session_path %> |
 		 	<%= link_to "Register Now!", new_user_registration_path %>
		</div>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Just Rate" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,700,300|Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="main" role="main">
      <div class="container">
        <%= render 'layouts/user' %>
        <header class="logo-container">
          <div class="row-fluid">
            <%= link_to root_url do %>
              <div class="logo span4">
                <i class="icon-star"></i>
                Just Rate
              </div>
            <% end %>
            <div class="top-slogan span5">
            </div>
            <div class="top-banner span3 white-container">
              Banner
            </div>
          </div>
        </header>
        <header class="navbar">
          <nav class="navbar-inner">
            <div class="container">
              <%= render 'layouts/navigation' %>
            </div>
          </nav>
        </header>
        <div class="content">
          <div class="span9">
            <%= render 'layouts/messages' %>
          </div>
          <div class="row-fluid">
            <div class="span9 yield-container white-container">
              <%= yield %>
            </div>
            <div class="span3 side-banners white-container">
              B<br />
              a<br />
              n<br />
              n<br />
              e<br />
              r<br />
              s
            </div>
          </div>
          <footer>
            <div class ="container"
            <%= render 'layouts/footernav' %>
          </div>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>