config/routes.rb
Justrate::Application.routes.draw do

  get "reviews/new" => "reviews#new_blank"
  post "reviews/create_blank" => "reviews#create_blank"
  get "users/new"
  get "users/create"

  get '/about_us' => 'static_page#about_us'
  get '/privacy' => 'static_page#privacy'
  get '/toc' => 'static_page#toc'

  devise_for :users, :controllers => {:confirmations => 'confirmations', :omniauth_callbacks => "omniauth_callbacks"}
  devise_scope :user do
    post "/confirm" => "confirmations#confirm"
  end

  devise_for :admins

  resources :users, :only => [:show, :edit, :update]
  resources :departments do
    get :course_list
  end
  resources :universities

  resources :courses do
    resources :reviews do
      member do
        post :vote_for
        post :vote_against
        post :flag
      end
      resources :comments, :shallow => true do
        get :reply
        post :new_reply
      end
    end
  end

  root :to => 'courses#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # Make sure the user is authenticated
  before_filter :authenticate_user!, except: [:index, :show, :destroy]
  before_filter :authenticate_admin!, only: [:destroy, :update]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # thumbs_up & thumbs_down for the reviews
  def vote_for
    @review = Review.find(params[:id])
    current_user.unvote_for(@review)
    current_user.vote_for(@review)
    respond_to do |format|
      format.html { redirect_to course_review_path(@review.course, @review) }
    end
  end

  def vote_against
    @review = Review.find(params[:id])
    current_user.unvote_for(@review)
    current_user.vote_against(@review)
    respond_to do |format|
      format.html { redirect_to course_review_path(@review.course, @review) }
    end
  end

  # Flag inappropriate for the reviews
  def flag 
    @review = Review.find(params[:id])

    @flag = @review.flags.new(params[:flag])
    @flag.flager = current_user

    respond_to do |format|
      if @flag.save
        format.html { redirect_to course_review_path(@review.course, @review), notice: 'Review has been flagged.' }
        format.json { render json: @flag, status: :created, location: @review}
      else
        format.html { redirect_to course_review_path(@review.course, @review), notice: 'You already flaged this.' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @course = Course.find(params[:course_id])
    @review = @course.reviews.find(params[:id])
    @comment = @review.comments.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @course = Course.find(params[:course_id])
    @review = @course.reviews.build

    @course.rating_entities.each do |rating_entity|
      @rating = rating_entity.ratings.build
      @review.ratings << @rating
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  def new_blank
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @course = Course.find(params[:course_id])
    @review = @course.reviews.new(params[:review])
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to course_review_path(@course, @review), notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_blank
    @department = Department.find(params[:department_id])
    @course = @department.courses.find(params[:course_id])

    respond_to do |format|
      format.html { redirect_to new_course_review_path(@course, @review) }
      format.json { render json: @review, status: :created, location: @review }
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to course_path(@review.course), notice: 'Review was successfully removed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
		end.join.html_safe
	end
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@course, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>
    Review information
  </legend>
  <%= f.input :title, label: false, placeholder: "Title" %>
  <%= f.input :text, label: false, placeholder: "Written review" %>

  <legend>
    Ratings
  </legend>
  <%= f.fields_for :ratings do |ratings_form| %>
    <%= ratings_form.input :rating_entity_id, as: :hidden, value: ratings_form.object.rating_entity.id %>
    <%= ratings_form.input :score, label: ratings_form.object.rating_entity.name, hint: ratings_form.object.rating_entity.description, as: :stars, num_of_stars: 5 %>
  <% end %>


  <div class="form-actions">
    <%= f.submit 'Create review', class: 'btn btn-success' %>
    <%= current_user.anonReviews? ? 'as anonmous' : "as #{current_user.name}" %>
  </div>
<% end %>

app/views/reviews/_reviews.html.erb
<% if reviews.empty? %>
  No reviews has been written yet. That means you can be first!
<% else %>
  <table class="table">
    <thead>
      <th>Course</th>
      <th>Course number</th>
      <th>Author</th>
      <th>Title</th>
      <th>Posted</th>
    </thead>
    <tbody>
      <% reviews.each_with_index do |review, index| %>
        <tr>
          <td><%= link_to review.course.name, review.course %></td>
          <td><%= review.course.course_number %></td>
          <td>
            <% if review.user.try(:anon_reviews?) or !review.user %>
              Anonymous
            <% else %>
              <%= review.user.name %></td>
            <% end %>
          <td><%= review.title %></td>
          <td><%= time_ago_in_words review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Course</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.course_id %></td>
    <td><%= review.text %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review for <%= @course.name %></h1>
<hr>
<%= render 'form' %>

app/views/reviews/new_blank.html.erb
<h1>New without course</h1>

<%= simple_form_for(@review, url: reviews_create_blank_path) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>
    1. Please select a department
  </legend>

  <div class="row-fluid">
    <%= select_tag "department_id", options_from_collection_for_select(Department.all, "id", "name"), class: 'span8', placeholder: "Please choose a department", include_blank: true %>
  </div>
  <hr>
  <div class="course hidden">
    <div class="row-fluid">
      <legend>
        2. Select a course
      </legend>
    </div>

    <div class="row-fluid">
      <%= select_tag "course_id", nil, class: 'span8', placeholder: "Please select a course", include_blank: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Continue', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<h1>
  <% if admin_signed_in? %>
    <%= link_to '<i class="icon-remove"></i>'.html_safe, course_review_path(@review.course.id, @review.id), method: :delete, confirm: 'Are you sure you want to remove this review?' %>
  <% end %>
  
  <%= @review.title %>
      |
    <i class='icon-thumbs-up'></i>
    <%= "#{@review.votes_for}" %>
    <i class='icon-thumbs-down'/></i>
    <%= "#{@review.votes_against}" %>
</h1>
<div class="row-fluid">
  <div class="span12">
    <%= @review.text %>
  </div>
</div>
<h3>Ratings</h3>
<% @review.ratings.each do |rating| %>
  <div class="row-fluid">
    <div class="span3">
      <%= rating.rating_entity.name %>
    </div>
    <div class="span5 stars">
      <% rating.score.to_i.times do |star| %>
        <i class="icon-star"></i>
      <% end %>
      <% (5 - rating.score.to_i).times do |star| %>
        <i class="icon-star-empty"></i>
      <% end %>
    </div>
  </div>
<% end %>

<% unless @review.user == current_user %>
  <hr>
  <%= link_to vote_for_course_review_path(@course, @review), method: :post, class: 'btn ' + (current_user.voted_for?(@review) ? 'btn-success' : '') do %>
    <i class="icon-thumbs-up"></i>
  <% end %>
  <%= link_to vote_against_course_review_path(@course, @review), method: :post, class: 'btn ' + (current_user.voted_against?(@review) ? 'btn-danger' : '') do %>
    <i class="icon-thumbs-down"></i>
  <% end %>
  <% if current_user and !current_user.flagged_reviews.include?(@review) %>
    <%=link_to 'Flag this as inappropriate', flag_course_review_path(@course, @review), method: :post %>
  <% else %>
    You already flagged this review
  <% end %>
<% end %>

<hr>

<h2>Comments</h2>

<%= render @review.comments.roots %>

<h3>Add comment</h3>
<%= render "comments/form" %>

app/views/reviews/vote_against.js.erb
alert('nope');

app/views/reviews/vote_for.js.erb
alert('yep');